### PR TITLE
[WIP] Fix UI Race Conditions

### LINKED ISSUE #143: UI & Worker Race Condition
It turns out that GitPython is not thread safe at all. We already knew that when we started, but we thought that you would at least be able to read from the same git repository from multiple threads. This seems to actually be not true. To fix this race condition it looks like the only way we can do it is by creating a `repo` object for each thread. 

To do this, we will need to redesign the Client a little to give the UI its own thread for reading from now on. We also need to make sure that the writing thread does not write while we are reading it in another thread. This will require some heavy work.

### PR DESCRIPTION
**Pull request by mahaloz**
On completion, this should close #143.

### CODE REVIEW

**Comment by mahaloz** [comment]
## Progress
After some extensive testing and research on [GitPython](https://github.com/gitpython-developers/GitPython), it has become clear to me that it is not possible to use GitPython with two threads acting on the same physical repo. There are many problems in place with GitPython that prevents us from making a simple fix to this. Here is one issue that shows the same problem:
https://github.com/gitpython-developers/GitPython/issues/584

I've almost finished testing using two `Git.Repo` instances in the client called `rw_repo` and `ro_repo`. I still have to make it work for calling `users()`, but as it stands right now, having two repo objects does not solve the problem. 

Should my plan not work after implementing it for `users()`, the only option left is to actually have two physical copies of the Git repo when we clone it down:
1. For rw operations from the worker thread
2. For ro operations from only the GUI thread

**Comment by ltfish** [comment]
What if all reads and writes to the Git repo are performed from one dedicated worker thread, and all other threads just queue Git repo read/write jobs to that one thread?

**Comment by mahaloz** [comment]
> What if all reads and writes to the Git repo are performed from one dedicated worker thread, and all other threads just queue Git repo read/write jobs to that one thread?

@ltfish we _kinda_ have something for that currently:
https://github.com/angr/binsync/blob/0b52424e77d57bb50d7bd156c0299c6b1de190fc/binsync/common/controller.py#L183

Basically, we have a central worker thread that assures that you are never writing and reading at the same time. The real problem happens from UI displays information found from Git. In general, through PyQt you are not allowed to call a UI function from another thread. This means from another thread we can't ask the UI to update and wait for the change to happen, we have to use signals...

This is all a long-winded way to say a lot of shit is fucked and it would take an _extensive_ to refactor to make this work. I think there may be a possible way to pull this off:
1. The first thread is the UI thread, it displays things 
2. The second thread is the Controller thread, it sends a signal every so many second to update the UI and current context
3. The third thread is Client thread, it queues and works on Git commands (commits, pull, push, checkout) 

Soooooo it may work out.

**Comment by ltfish** [comment]
> In general, through PyQt you are not allowed to call a UI function from another thread.

This might be what you need: https://github.com/angr/angr-management/blob/master/angrmanagement/logic/threads.py#L129

> Soooooo it may work out.

What you proposed makes sense to me. For GUI programs to work (with a good user experience), you'll want to put as few things on the UI thread as possible.

**Comment by mahaloz** [comment]
## Progress
I've completely rewritten the Client to make all Git operations work as atomic operations in one thread. This has fully removed the race conditions! Yay! 

Bad news, this has also made the client much more stalling when doing fast state computation operations. To make this faster, I've introduced a caching system.

The current problem is that the cache is a class member in the Client class, but when it's accessed from the Worker thread it makes a complete duplicate of the cache (which means last round stuff is lost). 

The way to fix this I think is to instead of accessing the member from the client to pass a reference of the object around through every job execution cycle, then reference it there. I still need to go through and make this work.

I also need to cleanup the worker thread in the Controller to look more like the Client one.

**Pull request merged**
